global using System;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel.DataAnnotations;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Threading;

global using Atc.DependencyInjection;
global using Atc.SourceGenerators.Annotations;
global using Atc.Wpf.Notifications;
global using Atc.XamlToolkit.Controls.Attributes;
global using Atc.XamlToolkit.Messaging;
global using Atc.XamlToolkit.Mvvm;

global using Linksoft.CameraWall.Wpf.Services.Internal;
global using Linksoft.VideoEngine;
global using Linksoft.VideoSurveillance.Enums;
global using Linksoft.VideoSurveillance.Models.Settings;
global using Linksoft.VideoSurveillance.Wpf.Core;
global using Linksoft.VideoSurveillance.Wpf.Core.Events;
global using Linksoft.VideoSurveillance.Wpf.Core.Factories;
global using Linksoft.VideoSurveillance.Wpf.Core.Messages;
global using Linksoft.VideoSurveillance.Wpf.Core.Models;
global using Linksoft.VideoSurveillance.Wpf.Core.Resources;
global using Linksoft.VideoSurveillance.Wpf.Core.Services;
global using Linksoft.VideoSurveillance.Wpf.Core.UserControls;
global using Microsoft.Extensions.Logging;

global using BoundingBox = Linksoft.VideoSurveillance.Models.BoundingBox;
global using CameraLayoutItem = Linksoft.VideoSurveillance.Models.CameraLayoutItem;
global using ConnectionState = Atc.Network.ConnectionState;
global using IGitHubReleaseService = Linksoft.VideoSurveillance.Services.IGitHubReleaseService;
global using IMediaCleanupService = Linksoft.VideoSurveillance.Services.IMediaCleanupService;
global using IMediaPipeline = Linksoft.VideoSurveillance.Services.IMediaPipeline;
global using IMotionDetectionService = Linksoft.VideoSurveillance.Services.IMotionDetectionService;
global using IRecordingSegmentationService = Linksoft.VideoSurveillance.Services.IRecordingSegmentationService;
global using IThumbnailGeneratorService = Linksoft.VideoSurveillance.Services.IThumbnailGeneratorService;
global using MediaCleanupCompletedEventArgs = Linksoft.VideoSurveillance.Events.MediaCleanupCompletedEventArgs;
global using MediaCleanupResult = Linksoft.VideoSurveillance.Models.MediaCleanupResult;
global using MotionDetectedEventArgs = Linksoft.VideoSurveillance.Events.MotionDetectedEventArgs;
global using RecordingSegmentedEventArgs = Linksoft.VideoSurveillance.Events.RecordingSegmentedEventArgs;
global using RecordingSession = Linksoft.VideoSurveillance.Models.RecordingSession;
global using RecordingStateChangedEventArgs = Linksoft.VideoSurveillance.Events.RecordingStateChangedEventArgs;
global using SegmentationReason = Linksoft.VideoSurveillance.Events.SegmentationReason;
global using TimelapseFrameCapturedEventArgs = Linksoft.VideoSurveillance.Events.TimelapseFrameCapturedEventArgs;