global using System;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Media;
global using System.Net.Http;
global using System.Reflection;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Input;
global using System.Windows.Interop;
global using System.Windows.Media;
global using System.Windows.Media.Animation;
global using System.Windows.Media.Imaging;
global using System.Windows.Threading;

global using Atc;
global using Atc.DependencyInjection;
global using Atc.Helpers;
global using Atc.Network.Helpers;
global using Atc.SourceGenerators.Annotations;
global using Atc.Wpf.Components.Dialogs;
global using Atc.Wpf.Components.Selectors;
global using Atc.Wpf.DependencyObjects;
global using Atc.Wpf.Forms;
global using Atc.Wpf.Helpers;
global using Atc.Wpf.Network;
global using Atc.Wpf.Notifications;
global using Atc.Wpf.Translation;
global using Atc.XamlToolkit.Controls.Attributes;
global using Atc.XamlToolkit.Messaging;
global using Atc.XamlToolkit.Mvvm;

global using ControlzEx.Theming;

global using Linksoft.VideoEngine;

global using Linksoft.VideoSurveillance.Enums;
global using Linksoft.VideoSurveillance.Models.Overrides;
global using Linksoft.VideoSurveillance.Models.Settings;

global using Linksoft.Wpf.CameraWall.Dialogs;
global using Linksoft.Wpf.CameraWall.Events;
global using Linksoft.Wpf.CameraWall.Factories;
global using Linksoft.Wpf.CameraWall.Helpers;
global using Linksoft.Wpf.CameraWall.Messages;
global using Linksoft.Wpf.CameraWall.Models;
global using Linksoft.Wpf.CameraWall.Resources;
global using Linksoft.Wpf.CameraWall.Services;
global using Linksoft.Wpf.CameraWall.Services.Internal;
global using Linksoft.Wpf.CameraWall.UserControls;
global using Linksoft.Wpf.CameraWall.ValueConverters;
global using Linksoft.Wpf.CameraWall.Windows;
global using Microsoft.Extensions.Logging;
global using Microsoft.Win32;

global using AuthenticationSettings = Linksoft.Wpf.CameraWall.Models.Settings.AuthenticationSettings;
global using BoundingBox = Linksoft.VideoSurveillance.Models.BoundingBox;
global using CameraDisplaySettings = Linksoft.Wpf.CameraWall.Models.Settings.CameraDisplaySettings;
global using CameraLayoutItem = Linksoft.VideoSurveillance.Models.CameraLayoutItem;
global using CameraOverrides = Linksoft.VideoSurveillance.Models.CameraOverrides;
global using ConnectionSettings = Linksoft.Wpf.CameraWall.Models.Settings.ConnectionSettings;
global using ConnectionState = Atc.Network.ConnectionState;
global using IGitHubReleaseService = Linksoft.VideoSurveillance.Services.IGitHubReleaseService;
global using IMediaCleanupService = Linksoft.VideoSurveillance.Services.IMediaCleanupService;
global using IMediaPipeline = Linksoft.VideoSurveillance.Services.IMediaPipeline;
global using IMotionDetectionService = Linksoft.VideoSurveillance.Services.IMotionDetectionService;
global using IRecordingSegmentationService = Linksoft.VideoSurveillance.Services.IRecordingSegmentationService;
global using IThumbnailGeneratorService = Linksoft.VideoSurveillance.Services.IThumbnailGeneratorService;
global using MediaCleanupCompletedEventArgs = Linksoft.VideoSurveillance.Events.MediaCleanupCompletedEventArgs;
global using MediaCleanupResult = Linksoft.VideoSurveillance.Models.MediaCleanupResult;
global using MotionDetectedEventArgs = Linksoft.VideoSurveillance.Events.MotionDetectedEventArgs;
global using RecordingSegmentedEventArgs = Linksoft.VideoSurveillance.Events.RecordingSegmentedEventArgs;
global using RecordingSession = Linksoft.VideoSurveillance.Models.RecordingSession;
global using RecordingStateChangedEventArgs = Linksoft.VideoSurveillance.Events.RecordingStateChangedEventArgs;
global using SegmentationReason = Linksoft.VideoSurveillance.Events.SegmentationReason;
global using SmoothedBox = Linksoft.VideoSurveillance.Models.SmoothedBox;
global using StreamSettings = Linksoft.Wpf.CameraWall.Models.Settings.StreamSettings;
global using TimelapseFrameCapturedEventArgs = Linksoft.VideoSurveillance.Events.TimelapseFrameCapturedEventArgs;