namespace Linksoft.VideoSurveillance.Blazor.App.Services;

/// <summary>
/// Gateway service for API operations using generated endpoints.
/// This is a partial class split into files per first-path-segment.
/// Fields and constructor are auto-generated by the EndpointRegistration attribute.
/// </summary>
[EndpointRegistration("VideoSurveillance")]
[SuppressMessage(
    "Design",
    "CA1055:URI return values should not be strings",
    Justification = "Endpoint URLs are returned as strings to match the OpenAPI-generated client signature.")]
[SuppressMessage(
    "Design",
    "CA1056:URI properties should not be strings",
    Justification = "ApiBaseUrl is a configured string, not a constructed Uri; matches the OpenAPI-generated client signature.")]
public sealed partial class GatewayService
{
    private readonly JsonSerializerOptions jsonOptions = Atc.Serialization.JsonSerializerOptionsFactory.Create();

    public string ApiBaseUrl { get; internal set; } = string.Empty;
}