global using System.Collections.Concurrent;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Runtime.InteropServices;
global using System.Text;
global using Flyleaf.FFmpeg;
global using Linksoft.VideoEngine.Capture;
global using Linksoft.VideoEngine.Decoding;
global using Linksoft.VideoEngine.Demuxing;
global using Linksoft.VideoEngine.FFmpeg;
global using Linksoft.VideoEngine.Recording;
global using Microsoft.Extensions.Logging;
global using static Flyleaf.FFmpeg.Raw;
global using FFmpegLogLevel = Flyleaf.FFmpeg.LogLevel;