//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linksoft.Wpf.CameraWall.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linksoft.Wpf.CameraWall.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Linksoft Camera Wall.
        /// </summary>
        public static string AboutLinksoftCameraWall {
            get {
                return ResourceManager.GetString("AboutLinksoftCameraWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Camera.
        /// </summary>
        public static string AddCamera {
            get {
                return ResourceManager.GetString("AddCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add camera cancelled.
        /// </summary>
        public static string AddCameraCancelled {
            get {
                return ResourceManager.GetString("AddCameraCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Camera dialog....
        /// </summary>
        public static string AddCameraDialog {
            get {
                return ResourceManager.GetString("AddCameraDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added camera: {0}.
        /// </summary>
        public static string AddedCamera1 {
            get {
                return ResourceManager.GetString("AddedCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All cameras reconnected.
        /// </summary>
        public static string AllCamerasReconnected {
            get {
                return ResourceManager.GetString("AllCamerasReconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow drag and drop reorder.
        /// </summary>
        public static string AllowDragAndDropReorder {
            get {
                return ResourceManager.GetString("AllowDragAndDropReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Appearance.
        /// </summary>
        public static string ApplicationAppearance {
            get {
                return ResourceManager.GetString("ApplicationAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A professional camera wall application for monitoring multiple RTSP/HTTP camera streams in a dynamic grid layout..
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linksoft Camera Wall.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Camera.
        /// </summary>
        public static string AssignCamera {
            get {
                return ResourceManager.GetString("AssignCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign camera cancelled.
        /// </summary>
        public static string AssignCameraCancelled {
            get {
                return ResourceManager.GetString("AssignCameraCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Camera to Layout.
        /// </summary>
        public static string AssignCameraToLayout {
            get {
                return ResourceManager.GetString("AssignCameraToLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned camera: {0}.
        /// </summary>
        public static string AssignedCamera1 {
            get {
                return ResourceManager.GetString("AssignedCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to Layout.
        /// </summary>
        public static string AssignedToLayout {
            get {
                return ResourceManager.GetString("AssignedToLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically reconnect on failure.
        /// </summary>
        public static string AutoReconnectOnFailure {
            get {
                return ResourceManager.GetString("AutoReconnectOnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-save layout changes.
        /// </summary>
        public static string AutoSaveLayoutChanges {
            get {
                return ResourceManager.GetString("AutoSaveLayoutChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Cameras.
        /// </summary>
        public static string AvailableCameras {
            get {
                return ResourceManager.GetString("AvailableCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer duration (ms).
        /// </summary>
        public static string BufferDurationMs {
            get {
                return ResourceManager.GetString("BufferDurationMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of video data to buffer before playback. Higher values provide smoother playback but increase delay. Set to 0 for minimal buffering in low latency mode..
        /// </summary>
        public static string BufferDurationMsInfo {
            get {
                return ResourceManager.GetString("BufferDurationMsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Configuration.
        /// </summary>
        public static string CameraConfiguration {
            get {
                return ResourceManager.GetString("CameraConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Display.
        /// </summary>
        public static string CameraDisplay {
            get {
                return ResourceManager.GetString("CameraDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras.
        /// </summary>
        public static string Cameras {
            get {
                return ResourceManager.GetString("Cameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras:.
        /// </summary>
        public static string CamerasLabel {
            get {
                return ResourceManager.GetString("CamerasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string CameraStateChanged2 {
            get {
                return ResourceManager.GetString("CameraStateChanged2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        public static string CheckForUpdatesOnStartup {
            get {
                return ResourceManager.GetString("CheckForUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete camera &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmDeleteCamera1 {
            get {
                return ResourceManager.GetString("ConfirmDeleteCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete layout &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmDeleteLayout1 {
            get {
                return ResourceManager.GetString("ConfirmDeleteLayout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect cameras on startup.
        /// </summary>
        public static string ConnectCamerasOnStartup {
            get {
                return ResourceManager.GetString("ConnectCamerasOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected:.
        /// </summary>
        public static string ConnectedLabel {
            get {
                return ResourceManager.GetString("ConnectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        public static string ConnectionSettings {
            get {
                return ResourceManager.GetString("ConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successful.
        /// </summary>
        public static string ConnectionSuccessful {
            get {
                return ResourceManager.GetString("ConnectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timed out.
        /// </summary>
        public static string ConnectionTimedOut {
            get {
                return ResourceManager.GetString("ConnectionTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timeout (seconds).
        /// </summary>
        public static string ConnectionTimeoutSeconds {
            get {
                return ResourceManager.GetString("ConnectionTimeoutSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Layout.
        /// </summary>
        public static string CurrentLayoutGroup {
            get {
                return ResourceManager.GetString("CurrentLayoutGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version.
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Camera.
        /// </summary>
        public static string DeleteCamera {
            get {
                return ResourceManager.GetString("DeleteCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted camera: {0}.
        /// </summary>
        public static string DeletedCamera1 {
            get {
                return ResourceManager.GetString("DeletedCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted layout: {0}.
        /// </summary>
        public static string DeletedLayout1 {
            get {
                return ResourceManager.GetString("DeletedLayout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Layout.
        /// </summary>
        public static string DeleteLayout {
            get {
                return ResourceManager.GetString("DeleteLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name is required.
        /// </summary>
        public static string DisplayNameRequired {
            get {
                return ResourceManager.GetString("DisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name cannot exceed 256 characters.
        /// </summary>
        public static string DisplayNameTooLong {
            get {
                return ResourceManager.GetString("DisplayNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Latest.
        /// </summary>
        public static string DownloadLatest {
            get {
                return ResourceManager.GetString("DownloadLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Camera....
        /// </summary>
        public static string EditCamera {
            get {
                return ResourceManager.GetString("EditCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit camera cancelled.
        /// </summary>
        public static string EditCameraCancelled {
            get {
                return ResourceManager.GetString("EditCameraCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing camera: {0}.
        /// </summary>
        public static string EditingCamera1 {
            get {
                return ResourceManager.GetString("EditingCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable debug logging.
        /// </summary>
        public static string EnableDebugLogging {
            get {
                return ResourceManager.GetString("EnableDebugLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable recording on motion detection.
        /// </summary>
        public static string EnableRecordingOnMotion {
            get {
                return ResourceManager.GetString("EnableRecordingOnMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End IP.
        /// </summary>
        public static string EndIp {
            get {
                return ResourceManager.GetString("EndIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the new layout:.
        /// </summary>
        public static string EnterLayoutName {
            get {
                return ResourceManager.GetString("EnterLayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new name for the layout:.
        /// </summary>
        public static string EnterNewLayoutName {
            get {
                return ResourceManager.GetString("EnterNewLayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries.
        /// </summary>
        public static string Entries {
            get {
                return ResourceManager.GetString("Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: {0}.
        /// </summary>
        public static string FailedWithStatus1 {
            get {
                return ResourceManager.GetString("FailedWithStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen: {0}.
        /// </summary>
        public static string FullScreenCamera1 {
            get {
                return ResourceManager.GetString("FullScreenCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen view for {0} will be implemented..
        /// </summary>
        public static string FullScreenNotImplemented1 {
            get {
                return ResourceManager.GetString("FullScreenNotImplemented1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Layout.
        /// </summary>
        public static string GridLayout {
            get {
                return ResourceManager.GetString("GridLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable hardware acceleration.
        /// </summary>
        public static string HardwareAcceleration {
            get {
                return ResourceManager.GetString("HardwareAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply UI settings.
        /// </summary>
        public static string InitializeApplyUISettings {
            get {
                return ResourceManager.GetString("InitializeApplyUISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize camera engine.
        /// </summary>
        public static string InitializeCameraEngine {
            get {
                return ResourceManager.GetString("InitializeCameraEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string InitializeComplete {
            get {
                return ResourceManager.GetString("InitializeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load configuration.
        /// </summary>
        public static string InitializeLoadConfiguration {
            get {
                return ResourceManager.GetString("InitializeLoadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load main window.
        /// </summary>
        public static string InitializeLoadMainWindow {
            get {
                return ResourceManager.GetString("InitializeLoadMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start host.
        /// </summary>
        public static string InitializeStartHost {
            get {
                return ResourceManager.GetString("InitializeStartHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A camera with this IP address already exists.
        /// </summary>
        public static string IpAddressAlreadyExists {
            get {
                return ResourceManager.GetString("IpAddressAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address is required.
        /// </summary>
        public static string IpAddressRequired {
            get {
                return ResourceManager.GetString("IpAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version.
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout updated: {0} added, {1} removed.
        /// </summary>
        public static string LayoutCamerasUpdated2 {
            get {
                return ResourceManager.GetString("LayoutCamerasUpdated2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout created: {0}.
        /// </summary>
        public static string LayoutCreated1 {
            get {
                return ResourceManager.GetString("LayoutCreated1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A layout with this name already exists.
        /// </summary>
        public static string LayoutNameAlreadyExists {
            get {
                return ResourceManager.GetString("LayoutNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout order updated.
        /// </summary>
        public static string LayoutOrderUpdated {
            get {
                return ResourceManager.GetString("LayoutOrderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout renamed: {0} → {1}.
        /// </summary>
        public static string LayoutRenamed2 {
            get {
                return ResourceManager.GetString("LayoutRenamed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layouts.
        /// </summary>
        public static string Layouts {
            get {
                return ResourceManager.GetString("Layouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} camera(s).
        /// </summary>
        public static string LoadedCameras1 {
            get {
                return ResourceManager.GetString("LoadedCameras1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded layout: {0}.
        /// </summary>
        public static string LoadedLayout1 {
            get {
                return ResourceManager.GetString("LoadedLayout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file folder.
        /// </summary>
        public static string LogFilePath {
            get {
                return ResourceManager.GetString("LogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low latency mode.
        /// </summary>
        public static string LowLatencyMode {
            get {
                return ResourceManager.GetString("LowLatencyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max latency (ms).
        /// </summary>
        public static string MaxLatencyMs {
            get {
                return ResourceManager.GetString("MaxLatencyMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed delay in milliseconds before the player skips frames to catch up. Lower values reduce delay but may cause stuttering on slow connections..
        /// </summary>
        public static string MaxLatencyMsInfo {
            get {
                return ResourceManager.GetString("MaxLatencyMsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum reconnect attempts.
        /// </summary>
        public static string MaxReconnectAttempts {
            get {
                return ResourceManager.GetString("MaxReconnectAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move all to assigned.
        /// </summary>
        public static string MoveAllToAssigned {
            get {
                return ResourceManager.GetString("MoveAllToAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move all to available.
        /// </summary>
        public static string MoveAllToAvailable {
            get {
                return ResourceManager.GetString("MoveAllToAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected to assigned.
        /// </summary>
        public static string MoveToAssigned {
            get {
                return ResourceManager.GetString("MoveToAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected to available.
        /// </summary>
        public static string MoveToAvailable {
            get {
                return ResourceManager.GetString("MoveToAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Scanner - Find Cameras.
        /// </summary>
        public static string NetworkScannerHeader {
            get {
                return ResourceManager.GetString("NetworkScannerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Camera.
        /// </summary>
        public static string NewCamera {
            get {
                return ResourceManager.GetString("NewCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Layout.
        /// </summary>
        public static string NewLayout {
            get {
                return ResourceManager.GetString("NewLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New layout cancelled.
        /// </summary>
        public static string NewLayoutCancelled {
            get {
                return ResourceManager.GetString("NewLayoutCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available!.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All cameras are already in this layout..
        /// </summary>
        public static string NoCamerasAvailable {
            get {
                return ResourceManager.GetString("NoCamerasAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cameras configured. Add a camera to get started..
        /// </summary>
        public static string NoCamerasConfigured {
            get {
                return ResourceManager.GetString("NoCamerasConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not tested.
        /// </summary>
        public static string NotTested {
            get {
                return ResourceManager.GetString("NotTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay opacity.
        /// </summary>
        public static string OverlayOpacity {
            get {
                return ResourceManager.GetString("OverlayOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Position.
        /// </summary>
        public static string OverlayPosition {
            get {
                return ResourceManager.GetString("OverlayPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Settings.
        /// </summary>
        public static string OverlaySettings {
            get {
                return ResourceManager.GetString("OverlaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play notification sound.
        /// </summary>
        public static string PlayNotificationSound {
            get {
                return ResourceManager.GetString("PlayNotificationSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be between 1 and 65535.
        /// </summary>
        public static string PortRangeError {
            get {
                return ResourceManager.GetString("PortRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports.
        /// </summary>
        public static string Ports {
            get {
                return ResourceManager.GetString("Ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position changed: {0}.
        /// </summary>
        public static string PositionChanged1 {
            get {
                return ResourceManager.GetString("PositionChanged1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ESC to exit full screen.
        /// </summary>
        public static string PressEscToExit {
            get {
                return ResourceManager.GetString("PressEscToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect All.
        /// </summary>
        public static string ReconnectAll {
            get {
                return ResourceManager.GetString("ReconnectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect delay (seconds).
        /// </summary>
        public static string ReconnectDelaySeconds {
            get {
                return ResourceManager.GetString("ReconnectDelaySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting....
        /// </summary>
        public static string Reconnecting {
            get {
                return ResourceManager.GetString("Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting all cameras....
        /// </summary>
        public static string ReconnectingAllCameras {
            get {
                return ResourceManager.GetString("ReconnectingAllCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording format.
        /// </summary>
        public static string RecordingFormat {
            get {
                return ResourceManager.GetString("RecordingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording folder.
        /// </summary>
        public static string RecordingPath {
            get {
                return ResourceManager.GetString("RecordingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Settings.
        /// </summary>
        public static string RecordingSettings {
            get {
                return ResourceManager.GetString("RecordingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Layout.
        /// </summary>
        public static string RenameLayout {
            get {
                return ResourceManager.GetString("RenameLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename layout cancelled.
        /// </summary>
        public static string RenameLayoutCancelled {
            get {
                return ResourceManager.GetString("RenameLayoutCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Defaults.
        /// </summary>
        public static string RestoreDefaults {
            get {
                return ResourceManager.GetString("RestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTSP transport.
        /// </summary>
        public static string RtspTransport {
            get {
                return ResourceManager.GetString("RtspTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP is more reliable but may have higher latency. UDP is faster but packets may be lost on unstable networks..
        /// </summary>
        public static string RtspTransportInfo {
            get {
                return ResourceManager.GetString("RtspTransportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Snapshot.
        /// </summary>
        public static string SaveSnapshot {
            get {
                return ResourceManager.GetString("SaveSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a camera to add to this layout:.
        /// </summary>
        public static string SelectCameraToAssign {
            get {
                return ResourceManager.GetString("SelectCameraToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select log folder....
        /// </summary>
        public static string SelectLogFolder {
            get {
                return ResourceManager.GetString("SelectLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select recording folder....
        /// </summary>
        public static string SelectRecordingFolder {
            get {
                return ResourceManager.GetString("SelectRecordingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select snapshot folder....
        /// </summary>
        public static string SelectSnapshotFolder {
            get {
                return ResourceManager.GetString("SelectSnapshotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Startup.
        /// </summary>
        public static string SetAsStartup {
            get {
                return ResourceManager.GetString("SetAsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set startup layout: {0}.
        /// </summary>
        public static string SetStartupLayout1 {
            get {
                return ResourceManager.GetString("SetStartupLayout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show connection status.
        /// </summary>
        public static string ShowCameraOverlayConnectionStatus {
            get {
                return ResourceManager.GetString("ShowCameraOverlayConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show camera description.
        /// </summary>
        public static string ShowCameraOverlayDescription {
            get {
                return ResourceManager.GetString("ShowCameraOverlayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show current time.
        /// </summary>
        public static string ShowCameraOverlayTime {
            get {
                return ResourceManager.GetString("ShowCameraOverlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show camera title.
        /// </summary>
        public static string ShowCameraOverlayTitle {
            get {
                return ResourceManager.GetString("ShowCameraOverlayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Full Screen.
        /// </summary>
        public static string ShowInFullScreen {
            get {
                return ResourceManager.GetString("ShowInFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification on disconnect.
        /// </summary>
        public static string ShowNotificationOnDisconnect {
            get {
                return ResourceManager.GetString("ShowNotificationOnDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification on reconnect.
        /// </summary>
        public static string ShowNotificationOnReconnect {
            get {
                return ResourceManager.GetString("ShowNotificationOnReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Only Reachable.
        /// </summary>
        public static string ShowOnlyReachable {
            get {
                return ResourceManager.GetString("ShowOnlyReachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Only With Open Ports.
        /// </summary>
        public static string ShowOnlyWithOpenPorts {
            get {
                return ResourceManager.GetString("ShowOnlyWithOpenPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default snapshot folder.
        /// </summary>
        public static string SnapshotDirectory {
            get {
                return ResourceManager.GetString("SnapshotDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot Settings.
        /// </summary>
        public static string SnapshotSettings {
            get {
                return ResourceManager.GetString("SnapshotSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start IP.
        /// </summary>
        public static string StartIp {
            get {
                return ResourceManager.GetString("StartIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start maximized (fullscreen).
        /// </summary>
        public static string StartMaximized {
            get {
                return ResourceManager.GetString("StartMaximized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with ribbon collapsed.
        /// </summary>
        public static string StartRibbonCollapsed {
            get {
                return ResourceManager.GetString("StartRibbonCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        public static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open stream.
        /// </summary>
        public static string StreamOpenFailed {
            get {
                return ResourceManager.GetString("StreamOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Left.
        /// </summary>
        public static string SwapLeft {
            get {
                return ResourceManager.GetString("SwapLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Right.
        /// </summary>
        public static string SwapRight {
            get {
                return ResourceManager.GetString("SwapRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Snapshot.
        /// </summary>
        public static string TakeSnapshot {
            get {
                return ResourceManager.GetString("TakeSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result.
        /// </summary>
        public static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Color.
        /// </summary>
        public static string ThemeAccent {
            get {
                return ResourceManager.GetString("ThemeAccent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeBase {
            get {
                return ResourceManager.GetString("ThemeBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check for updates. Please check your internet connection..
        /// </summary>
        public static string UnableToCheckForUpdates {
            get {
                return ResourceManager.GetString("UnableToCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated camera: {0}.
        /// </summary>
        public static string UpdatedCamera1 {
            get {
                return ResourceManager.GetString("UpdatedCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use low latency mode.
        /// </summary>
        public static string UseLowLatencyMode {
            get {
                return ResourceManager.GetString("UseLowLatencyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables optimized settings for minimal delay. Reduces buffer size and disables some processing to achieve near real-time video playback..
        /// </summary>
        public static string UseLowLatencyModeInfo {
            get {
                return ResourceManager.GetString("UseLowLatencyModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video quality.
        /// </summary>
        public static string VideoQuality {
            get {
                return ResourceManager.GetString("VideoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Settings.
        /// </summary>
        public static string VideoSettings {
            get {
                return ResourceManager.GetString("VideoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are up to date..
        /// </summary>
        public static string YouAreUpToDate {
            get {
                return ResourceManager.GetString("YouAreUpToDate", resourceCulture);
            }
        }
    }
}
