//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linksoft.Wpf.CameraWall.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linksoft.Wpf.CameraWall.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Linksoft Camera Wall.
        /// </summary>
        public static string AboutLinksoftCameraWall {
            get {
                return ResourceManager.GetString("AboutLinksoftCameraWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Camera.
        /// </summary>
        public static string AddCamera {
            get {
                return ResourceManager.GetString("AddCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add camera cancelled.
        /// </summary>
        public static string AddCameraCancelled {
            get {
                return ResourceManager.GetString("AddCameraCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Camera dialog....
        /// </summary>
        public static string AddCameraDialog {
            get {
                return ResourceManager.GetString("AddCameraDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added camera: {0}.
        /// </summary>
        public static string AddedCamera1 {
            get {
                return ResourceManager.GetString("AddedCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All cameras refreshed.
        /// </summary>
        public static string AllCamerasRefreshed {
            get {
                return ResourceManager.GetString("AllCamerasRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A professional camera wall application for monitoring multiple RTSP/HTTP camera streams in a dynamic grid layout..
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Configuration.
        /// </summary>
        public static string CameraConfiguration {
            get {
                return ResourceManager.GetString("CameraConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string CameraStateChanged2 {
            get {
                return ResourceManager.GetString("CameraStateChanged2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete camera &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmDeleteCamera1 {
            get {
                return ResourceManager.GetString("ConfirmDeleteCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete layout &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmDeleteLayout1 {
            get {
                return ResourceManager.GetString("ConfirmDeleteLayout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successful.
        /// </summary>
        public static string ConnectionSuccessful {
            get {
                return ResourceManager.GetString("ConnectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timed out.
        /// </summary>
        public static string ConnectionTimedOut {
            get {
                return ResourceManager.GetString("ConnectionTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version.
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Camera.
        /// </summary>
        public static string DeleteCamera {
            get {
                return ResourceManager.GetString("DeleteCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted camera: {0}.
        /// </summary>
        public static string DeletedCamera1 {
            get {
                return ResourceManager.GetString("DeletedCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted layout: {0}.
        /// </summary>
        public static string DeletedLayout1 {
            get {
                return ResourceManager.GetString("DeletedLayout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Layout.
        /// </summary>
        public static string DeleteLayout {
            get {
                return ResourceManager.GetString("DeleteLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name is required.
        /// </summary>
        public static string DisplayNameRequired {
            get {
                return ResourceManager.GetString("DisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name cannot exceed 256 characters.
        /// </summary>
        public static string DisplayNameTooLong {
            get {
                return ResourceManager.GetString("DisplayNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Latest.
        /// </summary>
        public static string DownloadLatest {
            get {
                return ResourceManager.GetString("DownloadLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Camera....
        /// </summary>
        public static string EditCamera {
            get {
                return ResourceManager.GetString("EditCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit camera cancelled.
        /// </summary>
        public static string EditCameraCancelled {
            get {
                return ResourceManager.GetString("EditCameraCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing camera: {0}.
        /// </summary>
        public static string EditingCamera1 {
            get {
                return ResourceManager.GetString("EditingCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End IP.
        /// </summary>
        public static string EndIp {
            get {
                return ResourceManager.GetString("EndIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the new layout:.
        /// </summary>
        public static string EnterLayoutName {
            get {
                return ResourceManager.GetString("EnterLayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries.
        /// </summary>
        public static string Entries {
            get {
                return ResourceManager.GetString("Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: {0}.
        /// </summary>
        public static string FailedWithStatus1 {
            get {
                return ResourceManager.GetString("FailedWithStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen: {0}.
        /// </summary>
        public static string FullScreenCamera1 {
            get {
                return ResourceManager.GetString("FullScreenCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen view for {0} will be implemented..
        /// </summary>
        public static string FullScreenNotImplemented1 {
            get {
                return ResourceManager.GetString("FullScreenNotImplemented1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A camera with this IP address already exists.
        /// </summary>
        public static string IpAddressAlreadyExists {
            get {
                return ResourceManager.GetString("IpAddressAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address is required.
        /// </summary>
        public static string IpAddressRequired {
            get {
                return ResourceManager.GetString("IpAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version.
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout created: {0}.
        /// </summary>
        public static string LayoutCreated1 {
            get {
                return ResourceManager.GetString("LayoutCreated1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A layout with this name already exists.
        /// </summary>
        public static string LayoutNameAlreadyExists {
            get {
                return ResourceManager.GetString("LayoutNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} camera(s).
        /// </summary>
        public static string LoadedCameras1 {
            get {
                return ResourceManager.GetString("LoadedCameras1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded layout: {0}.
        /// </summary>
        public static string LoadedLayout1 {
            get {
                return ResourceManager.GetString("LoadedLayout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Scanner - Find Cameras.
        /// </summary>
        public static string NetworkScannerHeader {
            get {
                return ResourceManager.GetString("NetworkScannerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Camera.
        /// </summary>
        public static string NewCamera {
            get {
                return ResourceManager.GetString("NewCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Layout.
        /// </summary>
        public static string NewLayout {
            get {
                return ResourceManager.GetString("NewLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New layout cancelled.
        /// </summary>
        public static string NewLayoutCancelled {
            get {
                return ResourceManager.GetString("NewLayoutCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available!.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cameras configured. Add a camera to get started..
        /// </summary>
        public static string NoCamerasConfigured {
            get {
                return ResourceManager.GetString("NoCamerasConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not tested.
        /// </summary>
        public static string NotTested {
            get {
                return ResourceManager.GetString("NotTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Position.
        /// </summary>
        public static string OverlayPosition {
            get {
                return ResourceManager.GetString("OverlayPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be between 1 and 65535.
        /// </summary>
        public static string PortRangeError {
            get {
                return ResourceManager.GetString("PortRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports.
        /// </summary>
        public static string Ports {
            get {
                return ResourceManager.GetString("Ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position changed: {0}.
        /// </summary>
        public static string PositionChanged1 {
            get {
                return ResourceManager.GetString("PositionChanged1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ESC to exit full screen.
        /// </summary>
        public static string PressEscToExit {
            get {
                return ResourceManager.GetString("PressEscToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting....
        /// </summary>
        public static string Reconnecting {
            get {
                return ResourceManager.GetString("Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing all cameras....
        /// </summary>
        public static string RefreshingAllCameras {
            get {
                return ResourceManager.GetString("RefreshingAllCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Snapshot.
        /// </summary>
        public static string SaveSnapshot {
            get {
                return ResourceManager.GetString("SaveSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set startup layout: {0}.
        /// </summary>
        public static string SetStartupLayout1 {
            get {
                return ResourceManager.GetString("SetStartupLayout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Full Screen.
        /// </summary>
        public static string ShowInFullScreen {
            get {
                return ResourceManager.GetString("ShowInFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Only Reachable.
        /// </summary>
        public static string ShowOnlyReachable {
            get {
                return ResourceManager.GetString("ShowOnlyReachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Only With Open Ports.
        /// </summary>
        public static string ShowOnlyWithOpenPorts {
            get {
                return ResourceManager.GetString("ShowOnlyWithOpenPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start IP.
        /// </summary>
        public static string StartIp {
            get {
                return ResourceManager.GetString("StartIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Left.
        /// </summary>
        public static string SwapLeft {
            get {
                return ResourceManager.GetString("SwapLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Right.
        /// </summary>
        public static string SwapRight {
            get {
                return ResourceManager.GetString("SwapRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Snapshot.
        /// </summary>
        public static string TakeSnapshot {
            get {
                return ResourceManager.GetString("TakeSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result.
        /// </summary>
        public static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check for updates. Please check your internet connection..
        /// </summary>
        public static string UnableToCheckForUpdates {
            get {
                return ResourceManager.GetString("UnableToCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated camera: {0}.
        /// </summary>
        public static string UpdatedCamera1 {
            get {
                return ResourceManager.GetString("UpdatedCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are up to date..
        /// </summary>
        public static string YouAreUpToDate {
            get {
                return ResourceManager.GetString("YouAreUpToDate", resourceCulture);
            }
        }
    }
}
