#pragma warning disable CA1056 // URI properties should not be strings

namespace Linksoft.VideoSurveillance.BlazorApp.Services;

/// <summary>
/// Gateway service for API operations using generated endpoints.
/// This is a partial class split into files per first-path-segment.
/// Fields and constructor are auto-generated by the EndpointRegistration attribute.
/// </summary>
[EndpointRegistration("VideoSurveillance")]
public sealed partial class GatewayService
{
    private readonly JsonSerializerOptions jsonOptions = Atc.Serialization.JsonSerializerOptionsFactory.Create();

    public string ApiBaseUrl { get; internal set; } = string.Empty;
}